# Generated by Django 3.1 on 2020-08-16 07:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outcome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'expenditure',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenditureIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'expenditure_income',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenditureIncomeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('period', models.CharField(choices=[('monthly', 'monthly'), ('once', 'Once'), ('daily', 'Daily')], max_length=25)),
                ('expenditure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenditure.expenditureincome')),
            ],
            options={
                'db_table': 'expenditure_income_detail',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenditureOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'expenditure_outcome',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenditureOutcomeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=512)),
                ('rate', models.CharField(choices=[('percentage', '%'), ('amount', 'Amount')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('account', models.CharField(choices=[('credit', 'credit'), ('debit', 'Debit')], max_length=6)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenditure_category', to='outcome.outcomecategory')),
                ('income', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenditure.expenditureincomedetail')),
                ('outcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenditure.expenditureoutcomedetail')),
            ],
            options={
                'db_table': 'expenditure_outcome_detail',
                'ordering': ['-id'],
            },
        ),
    ]
