# Generated by Django 3.1 on 2020-08-21 13:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=512)),
                ('rate', models.CharField(choices=[('percentage', '%'), ('amount', 'Amount')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('account', models.CharField(choices=[('credit', 'credit'), ('debit', 'Debit')], max_length=6)),
            ],
            options={
                'db_table': 'outcome',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OutcomeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'outcome_template',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OutcomeTemplateDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_detail', to='outcome.outcome')),
                ('outcome_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_template_detail', to='outcome.outcometemplate')),
            ],
            options={
                'db_table': 'outcome_template_details',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OutcomeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('period', models.CharField(choices=[('monthly', 'monthly'), ('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=25)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='outcome.outcomecategory')),
            ],
            options={
                'db_table': 'outcome_category',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='outcome',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='outcome.outcomecategory'),
        ),
    ]
