# Generated by Django 4.1.2 on 2022-10-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outcomecategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outcometemplate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outcometemplatedetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
